config/routes.rb
Rails.application.routes.draw do

  root to: 'employees#index'
  resources :employee_imports

  post 'employee_imports/imports' => 'employee_imports#imports'
  match 'employees/sort_by_first_character' => 'employees#sort_by_first_character',via: [:get, :post], as: :sort_by_first_character

  resources :employees do
    collection do
      match 'index' => 'employees#index', via: [:get, :post], as: :search
    end
  end

  

end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base

	belongs_to :department

	max_paginates_per 10

	validates_presence_of :department_id, :ssn, :name, :phone_number, :city, :expense, :age, :email, :address, :salary

	validates :age,  numericality: { :greater_than => 20, :less_than_or_equal_to => 50 ,

										message: "only allows 20-50 age"
											}

	def self.find_name_with_specified_range(range)
		@emp = Employee.where(name: nil)
		name_start_with = range[0]
		upto_this_char =  range[2]
		employees = Employee.all
		employees.each do |em|
			[*(name_start_with..upto_this_char)].each do |letter|
				@emp << em if em.name.upcase.start_with?(letter)
			end
		end
		@emp
	end

	def self.find_name_with_specified_age(range)
		age_start_with = range[0..1]
		upto_this_age = range[3..4]
		@emp = Employee.where(age: [age_start_with..upto_this_age])
		@emp
	end

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			employee = find_by_ssn(row["ssn"]) || new
			employee.attributes = row
			employee.save
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Csv.new(file.path, nil, :ignore)
		when ".xls" then Excel.new(file.path, nil, :ignore)
		when ".xlsx" then Roo::Spreadsheet.open(file.path)
		else raise "Unknown file type: #{file.original_filename}"
		end
	end

	private

	  def employee_params
	    params.require(:employee).permit(:department_id, :ssn, :name, :phone_number, :address, :salary, :age, :expense, :city, :age)
	  end

end

app/models/employee_import.rb
class EmployeeImport

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
end

app/controllers/employee_imports_controller.rb
class EmployeeImportsController < ApplicationController

	def imports
		 Employee.import(params[:file])
		 redirect_to root_url, notice: "Imported Employee successfully. "
  	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index

		@employee = Employee.new
		if !(params[:employee]).blank?
			@q = Employee.ransack({"name_cont"=>params[:employee][:name],"city_eq"=>params[:employee][:city], "age_eq"=>params[:employee][:age]})
			@emp1 = @q.result.page params[:page]
		else
			@emp1 = Employee.all.page params[:page]
		end
		@employees = @emp1.order('name ASC')
		respond_to do |format|
			format.html
		end
	end


	def sort_by_first_character

		@employee = Employee.new
		
		 if params["name-sort"] != " " && params["age-sort"] == " "
			@emp = Employee.find_name_with_specified_range(params["name-sort"])
	
		elsif params["age-sort"]  != " " && params["name-sort"] == " "
			@emp = Employee.find_name_with_specified_age(params["age-sort"])
 		
 		elsif  params["age-sort"]  != " " && params["name-sort"] != " "
			age_start_with = params["age-sort"][0..1]
			upto_this_age = params["age-sort"][3..4]
			emp_with_name_intials_in_given_range = Employee.find_name_with_specified_range(params["name-sort"])
			@emp =  emp_with_name_intials_in_given_range.select { |emp| emp.age >= age_start_with.to_i && emp.age <= upto_this_age.to_i }

		else		
			@emp = Employee.all
		end
		@employees = Employee.where(id: @emp.map(&:id)).order('name ASC').page params[:page]
		render "index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employee_imports/new.html.erb
<%= form_tag({action: :imports}, multipart: true, url: employee_imports_imports_path) do %>
  <%= file_field_tag :file %>
  <div><%= submit_tag 'Import' %></div>
<% end %>

app/views/employees/_search.html.erb
<%= semantic_form_for @employee, :url => search_employees_path, :html => {:class => "form-inline list-unstyled"} do |form| %>
      <div class="form-group">
      <label>Employee Name:</label>
      <%= form.inputs do %>
      <%= form.input :name, :as => :select,
      :collection => Employee.uniq.pluck(:name),
      :input_html => {:class => "small_dropdown form-control", :placeholder => "Name"} %>
      </div>
      <div class="form-group">
      <label>City:</label>
      <%= form.input :city, :as => :select,
      :collection => Employee.uniq.pluck(:city),
      :input_html => {:class => "small_dropdown form-control"} %>
      </div>
      <div class="form-group">
      <label>Age:</label>
      <%= form.input :age, :as => :select,
      :collection => Employee.uniq.pluck(:age),
      :input_html => {:class => "small_dropdown form-control"} %>
      </div>

      <div class="form-group">
      <label>  </label>
      <%= form.submit :submit, :as => :button, class: "btn btn-success form-control" %>
      </div>
<% end %>
<% end %>

app/views/employees/_sort_by_first_letter.html.erb
<%= form_tag('/employees/sort_by_first_character',:html => {:class => "form-inline list-unstyled"}) do -%>
<div class="form-group form-inline">
	<label>Sort by Name first Char</label><%= select_tag 'name-sort', options_for_select([" ", 'A-M','N-Z']), :class => "small_dropdown form-control" %>
	<label>Sort By Age :-</label> </span><%= select_tag 'age-sort', options_for_select([" " ,'20-35','35-50']), :class => "small_dropdown form-control" %>
	  <div><%= submit_tag 'Search' %></div>
</div>
<% end -%>

app/views/employees/index.html.erb
<div class="container">
<%= render :partial => '/employees/search' %>

<%= render :partial => '/employees/sort_by_first_letter' %>

<table id="Employee">
  <tr>
    <th>Department_id</th>
    <th>Ssn</th>
    <th>Name</th>
    <th>Phone_number</th>
    <th>Address</th>
    <th>City</th>
    <th>Expense</th>
    <th>Age</th>
    <th>Salary</th>
  </tr>
<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.department_id %></td>
    <td><%= employee.ssn %></td>
    <td><%= employee.name %></td>
    <td><%= employee.phone_number %></td>
    <td><%= employee.address %></td>
    <td><%= employee.city %></td>
    <td><%= employee.expense %></td>
    <td><%= employee.age %></td>
    <td><%= employee.salary  %></td>
  </tr>
<% end %>
</table>

<p><%= link_to "Import employees", new_employee_import_path %></p>


<%= page_entries_info @employees %>
<%= paginate @employees %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoAppForMetasearchAndImportExecl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>